repos:
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      files: apiserver/
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      files: apiserver/
