services:

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ${PWD}/data:/data # unmount this after data loading is successful
    env_file:
      - ./deployment/db-variables.env
    expose:
      - 5432
    restart: always

  apiserver:
    image: apiserver
    build:
      context: .
      dockerfile: deployment/Dockerfile
    # volumes: # used for development purposes only
    #   - ${PWD}:/app
    env_file:
      - ./deployment/api-variables.env
    environment:
      - RERUN_MIGRATIONS=false
      - USE_FIXTURES=false
    expose:
      - 8080
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:6543:80
    depends_on:
      - apiserver

volumes:
  postgres-data:
