services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./deployment/db-variables.env
    expose:
      - 5432
    restart: always

  apiserver:
    image: apiserver
    build:
      context: .
      dockerfile: deployment/Dockerfile
    volumes:
      - ${PWD}:/app
    env_file:
      - ./deployment/api-variables.env
    environment:
      - RERUN_MIGRATIONS=true
      - USE_FIXTURES=true
    ports:
      - "6543:8080"
    restart: always
    depends_on:
      - db

  nextjs:
    image: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - apiserver

volumes:
  postgres-data:
