name: Django CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: test-user
          POSTGRES_PASSWORD: just-a-small-password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    env:
      DJANGO_SECRET_KEY: dmjr4k5!uuwt3==2u!cxe@0ym9r^o(iggi3#(e=qlc+===%6ey
      DB_USER: test-user
      DB_PASSWORD: just-a-small-password
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      PORT: 8080

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --only main

    - name: Wait for PostgreSQL to start
      run: |
        while ! pg_isready -h localhost -p 5432 > /dev/null 2> /dev/null; do
          sleep 1
        done

    - name: Run tests
      run: |
        cd apiserver/

        python manage.py makemigrations members
        python manage.py migrate members
        python manage.py loaddata person.json

        python manage.py test
